service: aws-lambda-gmail-reader
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
